import { FormEvent, useEffect, useState } from 'react';
import { ConceptCandidate, Feature, LearningCard, RepositoryFile, TeachingLevel, VerifiedTeaching, getAnalysis, getCardTeaching, getCards, getConcepts, getFeatures, getFiles, submitRepository } from './api';
import CallEvidence from './CallEvidence';
import LearningProgress from './LearningProgress';
import { LearningView, readLearningRoute, writeLearningRoute } from './learningRoute';
import './app.css';

const terminal = new Set(['READY','FAILED_TERMINAL','FAILED_EXHAUSTED']);
const teachingLevels: TeachingLevel[] = ['intermediate','advanced','deep'];
type View = LearningView;
type TeachingByCard = Record<string, Partial<Record<TeachingLevel, VerifiedTeaching>>>;
type TeachingFlags = Record<string, Partial<Record<TeachingLevel, boolean>>>;
type TeachingErrors = Record<string, Partial<Record<TeachingLevel, string>>>;

export default function App() {
  const initialRoute = readLearningRoute(window.location.search);
  const [url,setUrl]=useState('https://github.com/octocat/Hello-World');
  const [id,setId]=useState<string|undefined>(initialRoute.analysisId); const [state,setState]=useState(initialRoute.analysisId?'RESTORING':'IDLE');
  const [features,setFeatures]=useState<Feature[]>([]); const [files,setFiles]=useState<RepositoryFile[]>([]); const [concepts,setConcepts]=useState<ConceptCandidate[]>([]); const [cards,setCards]=useState<LearningCard[]>([]);
  const [view,setView]=useState<View>(initialRoute.view); const [error,setError]=useState<string>();
  const [teaching,setTeaching]=useState<TeachingByCard>({}); const [teachingLoading,setTeachingLoading]=useState<TeachingFlags>({}); const [teachingErrors,setTeachingErrors]=useState<TeachingErrors>({});
  async function submit(e:FormEvent){e.preventDefault();setError(undefined);setFeatures([]);setFiles([]);setConcepts([]);setCards([]);setTeaching({});setTeachingLoading({});setTeachingErrors({});setView('features');try{const r=await submitRepository(url.trim());setId(r.id);setState(r.state)}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function loadFiles(){if(!id||state!=='READY')return null;if(files.length)return files;const result=await getFiles(id);setFiles(result.files);return result.files}
  async function openFiles(){try{const loaded=await loadFiles();if(loaded)setView('files')}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function openConcepts(){if(!id||state!=='READY'||view==='features')return;try{const result=await getConcepts(id);setConcepts(result.concepts);setView('concepts')}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function openCards(){if(!id||state!=='READY'||view!=='concepts')return;try{const result=await getCards(id);setCards(result.cards);setView('cards')}catch(e){setError(e instanceof Error?e.message:String(e))}}
  async function requestTeaching(card:LearningCard, level:TeachingLevel){
    if(teaching[card.id]?.[level]||teachingLoading[card.id]?.[level])return;
    setTeachingErrors(current=>({...current,[card.id]:{...current[card.id],[level]:undefined}}));
    setTeachingLoading(current=>({...current,[card.id]:{...current[card.id],[level]:true}}));
    try{
      const result=await getCardTeaching(card.id,level);
      if(result.verified!==true||result.level!==level)throw new Error('Teaching response failed client verification');
      const allowedEvidence=new Set(card.evidence.map(item=>item.id));
      if(result.claims.length===0||result.claims.some(claim=>claim.evidence_ids.length===0||claim.evidence_ids.some(evidenceId=>!allowedEvidence.has(evidenceId))))throw new Error('Teaching response cited unknown evidence');
      setTeaching(current=>({...current,[card.id]:{...current[card.id],[level]:result}}));
    }catch(e){setTeachingErrors(current=>({...current,[card.id]:{...current[card.id],[level]:e instanceof Error?e.message:String(e)}}));}
    finally{setTeachingLoading(current=>({...current,[card.id]:{...current[card.id],[level]:false}}));}
  }
  useEffect(()=>{if(!initialRoute.analysisId)return;let cancelled=false;(async()=>{try{const a=await getAnalysis(initialRoute.analysisId!);if(cancelled)return;setState(a.state);if(a.error)setError(a.error);if(a.state!=='READY')return;const map=await getFeatures(initialRoute.analysisId!);if(cancelled)return;setFeatures(map.features);if(initialRoute.view==='features')return;const fileResult=await getFiles(initialRoute.analysisId!);if(cancelled)return;setFiles(fileResult.files);if(initialRoute.view==='files')return;const conceptResult=await getConcepts(initialRoute.analysisId!);if(cancelled)return;setConcepts(conceptResult.concepts);if(initialRoute.view==='concepts')return;const cardResult=await getCards(initialRoute.analysisId!);if(cancelled)return;setCards(cardResult.cards)}catch(e){if(!cancelled){setError(e instanceof Error?e.message:String(e));setState('FAILED_TERMINAL')}}})();return()=>{cancelled=true}},[]);
  useEffect(()=>{const next=writeLearningRoute(id,view);const current=`${window.location.pathname}${window.location.search}`;if(next!==current)window.history.replaceState(null,'',next)},[id,view]);
  useEffect(()=>{if(!id||terminal.has(state)||state==='RESTORING')return;const timer=setInterval(async()=>{try{const a=await getAnalysis(id);setState(a.state);if(a.state==='READY'){const map=await getFeatures(id);setFeatures(map.features)}if(a.error)setError(a.error)}catch(e){setError(e instanceof Error?e.message:String(e))}},1000);return()=>clearInterval(timer)},[id,state]);
  return <main><header><span className="eyebrow">CARD IN REPO</span><h1>Read the flow before the files.</h1><p>Paste a public GitHub repository. The first result is its feature and execution map, not a wall of code cards.</p></header>
    <form onSubmit={submit}><label htmlFor="repo">Public repository</label><div className="submitRow"><input id="repo" type="url" required value={url} onChange={e=>setUrl(e.target.value)} placeholder="https://github.com/owner/repo"/><button disabled={state!=='IDLE'&&!terminal.has(state)}>Map repo</button></div></form>
    {state!=='IDLE'&&<section className="status" aria-live="polite"><strong>{state}</strong><span>{id}</span></section>}{error&&<p className="error">{error}</p>}
    {state==='READY'&&view==='features'&&<section><div className="sectionTitle"><span>01</span><h2>Repository map</h2></div>{features.length===0?<p>No execution features were discovered.</p>:features.map((f,i)=><article className="feature" key={f.id}><div className="featureHead"><b>{String(i+1).padStart(2,'0')}</b><h3>{f.name}</h3></div><ol>{f.flow_steps.map((s,j)=><li key={`${s.symbol_id}-${j}`}><span>{s.symbol_name??s.symbol_id}</span>{s.relation&&<small>{s.relation}</small>}<CallEvidence calls={s.unresolved_calls}/></li>)}</ol></article>)}</section>}
    {state==='READY'&&view==='files'&&<section><div className="sectionTitle"><span>02</span><h2>File structure</h2></div><p>Static-analysis facts grouped by source file. Choose the flow first, then see where its symbols live.</p>{files.length===0?<p>No analyzed source files were discovered.</p>:files.map(file=><article className="feature file" key={file.path}><div className="featureHead"><b>PY</b><h3>{file.path}</h3></div><ol>{file.symbols.map(symbol=><li key={symbol.id}><span>{symbol.name}</span><small>{symbol.kind??'symbol'}{symbol.range?.start?.line?` · L${symbol.range.start.line}${symbol.range.end?.line?`–${symbol.range.end.line}`:''}`:''}</small></li>)}</ol></article>)}</section>}
    {state==='READY'&&view==='concepts'&&id&&<section><div className="sectionTitle"><span>03</span><h2>Concepts</h2></div><p>Concept candidates and Basic teaching are accepted only after server-side evidence verification.</p><LearningProgress analysisId={id} concepts={concepts}/>{concepts.length===0?<p>No evidence-backed concepts were discovered.</p>:concepts.map(concept=>{const evidenceById=new Map(concept.evidence.map(item=>[item.id,item]));return <article className="feature concept" key={concept.id}><div className="featureHead"><b>FLOW</b><h3>{concept.name}</h3></div><div className="basicTeaching" data-verified={concept.explanation.verified}><strong>Basic · verified</strong>{concept.explanation.claims.map((claim,index)=><p className="teachingClaim" key={`${concept.id}-claim-${index}`}>{claim.text} <small>{claim.evidence_ids.map(evidenceId=>{const evidence=evidenceById.get(evidenceId);return <span className="evidenceCitation" data-evidence-id={evidenceId} key={evidenceId}>[{evidence?.symbol_name??evidenceId}{evidence?.path?` · ${evidence.path}`:''}]</span>})}</small></p>)}</div><ol>{concept.evidence.map(item=><li id={`evidence-${item.id}`} key={item.id}><span>{item.symbol_name}</span><small>{item.path??'path unavailable'}{item.relation?` · ${item.relation}`:''}</small></li>)}</ol></article>})}</section>}
    {state==='READY'&&view==='cards'&&<section><div className="sectionTitle"><span>04</span><h2>Code cards</h2></div><p>Function-sized source cards follow the execution map. Basic is ready up front; deeper teaching is generated only when you ask for it and must cite this card's static evidence.</p>{cards.length===0?<p>No function cards were discovered.</p>:cards.map(card=>{const evidenceById=new Map(card.evidence.map(item=>[item.id,item]));return <article className="feature codeCard" key={card.id}><div className="featureHead"><b>{card.segment.count>1?`${card.segment.index+1}/${card.segment.count}`:'CODE'}</b><h3>{card.symbol_name}</h3></div><small>{card.path} · L{card.range.start.line}–{card.range.end.line}</small><pre><code>{card.source}</code></pre><div className="cardTeaching" data-verified={card.basic_explanation.verified}><strong>Basic · verified</strong>{card.basic_explanation.claims.map((claim,index)=><p className="teachingClaim" key={`${card.id}-claim-${index}`}>{claim.text} <small>{claim.evidence_ids.map(evidenceId=>{const evidence=evidenceById.get(evidenceId);return <span className="evidenceCitation" data-evidence-id={evidenceId} key={evidenceId}>[{evidence?.path??evidenceId}{evidence?` · L${evidence.range.start.line}–${evidence.range.end.line}`:''}]</span>})}</small></p>)}</div><div className="teachingControls" aria-label={`Deeper teaching for ${card.symbol_name}`}>{teachingLevels.map(level=><button type="button" key={level} disabled={Boolean(teachingLoading[card.id]?.[level]||teaching[card.id]?.[level])} onClick={()=>requestTeaching(card,level)}>{teachingLoading[card.id]?.[level]?`Loading ${level}…`:teaching[card.id]?.[level]?`${level} · verified`:`Explain ${level}`}</button>)}</div>{teachingLevels.map(level=>{const explanation=teaching[card.id]?.[level];const levelError=teachingErrors[card.id]?.[level];return <div key={`${card.id}-${level}`}>{explanation&&<div className="deeperTeaching" data-level={level} data-verified={explanation.verified}><strong>{level} · verified</strong>{explanation.claims.map((claim,index)=><p className="teachingClaim" key={`${card.id}-${level}-claim-${index}`}>{claim.text} <small>{claim.evidence_ids.map(evidenceId=>{const evidence=evidenceById.get(evidenceId);return <span className="evidenceCitation" data-evidence-id={evidenceId} key={evidenceId}>[{evidence?.path??evidenceId}{evidence?` · L${evidence.range.start.line}–${evidence.range.end.line}`:''}]</span>})}</small></p>)}</div>}{levelError&&<p className="teachingError" role="status">{level} teaching unavailable. Verified Basic remains unchanged.</p>}</div>})}</article>})}</section>}
    <nav aria-label="Learning views"><button className={view==='features'?'active':''} onClick={()=>setView('features')}>Feature map</button><button className={view==='files'?'active':''} disabled={state!=='READY'} onClick={openFiles}>Files</button><button className={view==='concepts'?'active':''} disabled={state!=='READY'||view==='features'} onClick={openConcepts}>Concepts</button><button className={view==='cards'?'active':''} disabled={state!=='READY'||view!=='concepts'} onClick={openCards}>Cards</button></nav>
  </main>
}
